-- ===================================================
-- 04_customer_analysis.sql
-- Customer behaviour analysis
--
-- Focus Area:
-- 1. Customer summary
-- 2. Revenue per customer
-- 3. Top customers by revenue
-- 4. Top 10% customer revenue contribution (Pareto analysis)
-- 5. Top 1% customer revenue contribution 
-- 6. Top 0.1% customer revenue contribution 
-- ===================================================

-- 1. Customer summary, basic summary of customers, orders, and revenue. Using valid sales row only.
SELECT 
    COUNT(DISTINCT CustomerID) AS customer_count,
    COUNT(DISTINCT Invoice) AS order_count,
    ROUND(SUM(Quantity * Price), 2) AS total_revenue
FROM online_retail_ii
WHERE Quantity > 0
  AND Price > 0
  AND CustomerID IS NOT NULL
  AND CustomerID <> '';

-- 2. Revenue per customer, total revenue, units purchased, and order count for each customer
SELECT
    CustomerID,
    ROUND(SUM(Quantity * Price), 2) AS revenue,
    SUM(Quantity) AS units_purchased,
    COUNT(DISTINCT Invoice) AS total_orders
FROM online_retail_ii
WHERE Quantity > 0
  AND Price > 0
  AND CustomerID IS NOT NULL
  AND CustomerID <> ''
GROUP BY CustomerID
ORDER BY revenue DESC;

-- 3. Top customers by revenue
SELECT
    CustomerID,
    ROUND(SUM(Quantity * Price), 2) AS revenue,
    SUM(Quantity) AS units_purchased,
    COUNT(DISTINCT Invoice) AS total_orders
FROM online_retail_ii
WHERE Quantity > 0
  AND Price > 0
  AND CustomerID IS NOT NULL
  AND CustomerID <> ''
GROUP BY CustomerID
ORDER BY revenue DESC
LIMIT 10;

-- 4. Top 10% customer revenue contribution, Check how much revenue is generated by the top 10% of customer ranked by revenue
WITH customer_rev AS (
    SELECT
        CustomerID,
        SUM(Quantity * Price) AS revenue
    FROM online_retail_ii
    WHERE Quantity > 0
      AND Price > 0
      AND CustomerID IS NOT NULL
      AND CustomerID <> ''
    GROUP BY CustomerID
),
totals AS (
    SELECT
        COUNT(*) AS total_customers,
        SUM(revenue) AS total_revenue
    FROM customer_rev
),
ranked AS (
    SELECT
        CustomerID,
        revenue,
        ROW_NUMBER() OVER (ORDER BY revenue DESC) AS rn
    FROM customer_rev
)
SELECT
    t.total_customers,
    ROUND(t.total_revenue, 2) AS total_revenue,
    CEIL(t.total_customers * 0.10) AS top_10pct_customers,
    ROUND(SUM(r.revenue), 2) AS top_10pct_revenue,
    ROUND(SUM(r.revenue) / t.total_revenue * 100, 2) AS top_10pct_revenue_percent
FROM ranked r
CROSS JOIN totals t
WHERE r.rn <= CEIL(t.total_customers * 0.10)
GROUP BY t.total_customers, t.total_revenue;

-- 5. Top 1% customer revenue contribution
WITH customer_rev AS (
    SELECT
        CustomerID,
        SUM(Quantity * Price) AS revenue
    FROM online_retail_ii
    WHERE Quantity > 0
      AND Price > 0
      AND CustomerID IS NOT NULL
      AND CustomerID <> ''
    GROUP BY CustomerID
),
totals AS (
    SELECT
        COUNT(*) AS total_customers,
        SUM(revenue) AS total_revenue
    FROM customer_rev
),
ranked AS (
    SELECT
        CustomerID,
        revenue,
        ROW_NUMBER() OVER (ORDER BY revenue DESC) AS rn
    FROM customer_rev
)
SELECT
    t.total_customers,
    ROUND(t.total_revenue, 2) AS total_revenue,
    CEIL(t.total_customers * 0.01) AS top_1pct_customers,
    ROUND(SUM(r.revenue), 2) AS top_1pct_revenue,
    ROUND(SUM(r.revenue) / t.total_revenue * 100, 2) AS top_1pct_revenue_percent
FROM ranked r
CROSS JOIN totals t
WHERE r.rn <= CEIL(t.total_customers * 0.01)
GROUP BY t.total_customers, t.total_revenue;

-- 6. Top 0.1% customer revenue contribution 
WITH customer_rev AS (
    SELECT
        CustomerID,
        SUM(Quantity * Price) AS revenue
    FROM online_retail_ii
    WHERE Quantity > 0
      AND Price > 0
      AND CustomerID IS NOT NULL
      AND CustomerID <> ''
    GROUP BY CustomerID
),
totals AS (
    SELECT
        COUNT(*) AS total_customers,
        SUM(revenue) AS total_revenue
    FROM customer_rev
),
ranked AS (
    SELECT
        CustomerID,
        revenue,
        ROW_NUMBER() OVER (ORDER BY revenue DESC) AS rn
    FROM customer_rev
)
SELECT
    t.total_customers,
    ROUND(t.total_revenue, 2) AS total_revenue,
    CEIL(t.total_customers * 0.001) AS top_0_1pct_customers,
    ROUND(SUM(r.revenue), 2) AS top_0_1pct_revenue,
    ROUND(SUM(r.revenue) / t.total_revenue * 100, 2) AS top_0_1pct_revenue_percent
FROM ranked r
CROSS JOIN totals t
WHERE r.rn <= CEIL(t.total_customers * 0.001)
GROUP BY t.total_customers, t.total_revenue;
